#!/usr/bin/env node
// Generates the vigilkit SBOM (Software Bill of Materials).
//
//   node scripts/generate-sbom.mjs       # write SBOM.md + sbom.spdx.json at repo root
//
// The dependency data is REUSED from THIRD-PARTY-NOTICES.md, which is
// generated by scripts/check-licenses.mjs --generate-notices (`pnpm notices`)
// and enforced by `pnpm check:licenses` in CI. Reading the committed notices
// instead of re-running the license scan keeps the SBOM consistent with the
// license verdict by construction (same table, same licenses, including the
// supplementary entries such as @webgpu/types that the root scan cannot see).
// If THIRD-PARTY-NOTICES.md is missing or stale, run `pnpm notices` first.
//
// Outputs:
//   SBOM.md          human-readable SBOM reference (mirrors the notices)
//   sbom.spdx.json   SPDX 2.3 JSON document (spdxVersion "SPDX-2.3")
//
// The two vendored WASM artifacts (libde265 LGPL-3.0, dav1d BSD-2-Clause AND
// CC0-1.0) are not npm dependencies and never appear in the scan; they are
// recorded as SPDX packages too, with their sha256 pins parsed from the
// vendored-artifacts section of the notices so the hashes stay in sync.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const NOTICES_FILE = join(ROOT, 'THIRD-PARTY-NOTICES.md');
const SBOM_MD_FILE = join(ROOT, 'SBOM.md');
const SBOM_SPDX_FILE = join(ROOT, 'sbom.spdx.json');

const REPO_URL = 'https://github.com/SnowCrescenter-tech/vigilkit';

/** Splits a markdown table row into its trimmed cells. */
function tableCells(line) {
  return line
    .split('|')
    .map((cell) => cell.trim())
    .filter((cell) => cell !== '');
}

/**
 * Parses THIRD-PARTY-NOTICES.md into the dependency table (name | version |
 * license | publisher) and the vendored-artifacts table (artifact | source |
 * license | verified-by). Returns null when the file is missing.
 */
function parseNotices(text) {
  const packages = [];
  const vendored = [];
  let inVendored = false;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line.startsWith('## ')) {
      inVendored = line.startsWith('## Vendored');
      continue;
    }
    if (!line.startsWith('|')) continue;
    const cells = tableCells(line);
    // A data row has at least name | version | license; the publisher cell is
    // often empty and collapses away after trimming (e.g. "| a | 1 | MIT |  |"
    // -> 3 cells). Header rows ("| Package | ... |", "| Artifact | ... |") and
    // the separator row ("| --- | --- | --- | --- |") are detected below.
    if (cells.length < 3) continue;
    if (/^---+$/.test(cells[0])) continue;
    if (cells[0] === 'Package' || cells[0] === 'Artifact') continue;
    if (inVendored) {
      vendored.push({
        artifact: cells[0],
        source: cells[1],
        license: cells[2],
        verifiedBy: cells[3] ?? '',
      });
    } else {
      packages.push({
        name: cells[0],
        version: cells[1],
        license: cells[2],
        publisher: cells[3] ?? '',
      });
    }
  }
  return { packages, vendored };
}

/** "MIT, CC-BY-3.0" -> "MIT AND CC-BY-3.0"; UNKNOWN/missing -> NOASSERTION. */
function toSpdxExpression(license) {
  if (!license || license === 'UNKNOWN') return 'NOASSERTION';
  return String(license)
    .split(/\s*,\s*/)
    .map((part) => part.trim())
    .filter(Boolean)
    .join(' AND ');
}

/** SPDX IDs must be unique per package: name + version, sanitized. */
function spdxId(name, version) {
  const slug = `${name}-${version}`.replace(/[^A-Za-z0-9.-]+/g, '-').replace(/^-+|-+$/g, '');
  return `SPDXRef-Package-${slug}`;
}

/** Extracts the sha256 pins (`<64 hex>`) from a vendored "Verified by" cell. */
function sha256Pins(verifiedBy) {
  return [...String(verifiedBy).matchAll(/`([0-9a-f]{64})`/g)].map((m) => m[1]);
}

/** Versions of the vendored sources, parsed from the notices "Source" cell. */
function sourceVersion(source) {
  const match = String(source).match(/@(\d+\.\d+\.\d+)/);
  return match ? match[1] : 'NOASSERTION';
}

function buildSpdxDoc(packages, vendored, created) {
  const dependencyPackages = packages.map((p) => ({
    name: p.name,
    SPDXID: spdxId(p.name, p.version),
    versionInfo: p.version,
    licenseConcluded: toSpdxExpression(p.license),
    downloadLocation: 'NOASSERTION',
    filesAnalyzed: false,
    supplier: 'NOASSERTION',
  }));

  // Vendored WASM artifacts: physically isolated, sha256-pinned at load time
  // (see the notices and examples/basic/vendor/*.sha256). licenseConcluded is
  // fixed per artifact — libde265 LGPL-3.0, dav1d BSD-2-Clause (core) AND
  // CC0-1.0 (wrapper) — while names, versions, and sha256 pins are parsed from
  // the notices so they cannot drift from the source offer.
  const vendoredPackages = vendored.map((v) => {
    const isLibde265 = /libde265/i.test(v.artifact);
    const [wasmSha, esmSha] = sha256Pins(v.verifiedBy);
    const name = isLibde265 ? 'libde265' : 'dav1d';
    return {
      name,
      SPDXID: isLibde265 ? 'SPDXRef-Package-libde265-wasm' : 'SPDXRef-Package-dav1d-wasm',
      versionInfo: sourceVersion(v.source),
      licenseConcluded: isLibde265 ? 'LGPL-3.0' : 'BSD-2-Clause AND CC0-1.0',
      downloadLocation: 'NOASSERTION',
      filesAnalyzed: false,
      supplier: 'NOASSERTION',
      comment:
        `Vendored WASM artifact (${v.artifact}); not an npm dependency, loaded at runtime ` +
        `with sha256 verification. wasm sha256 ${wasmSha ?? 'n/a'}; esm wrapper sha256 ${esmSha ?? 'n/a'}.`,
      attributionTexts: wasmSha ? [`sha256:${wasmSha}`] : [],
    };
  });

  return {
    spdxVersion: 'SPDX-2.3',
    dataLicense: 'CC0-1.0',
    SPDXID: 'SPDXRef-DOCUMENT',
    name: 'vigilkit',
    documentNamespace: `${REPO_URL}/sbom/spdx/${created.replace(/[:.]/g, '-')}`,
    creationInfo: {
      created,
      creators: ['Tool: vigilkit-generate-sbom'],
    },
    packages: [...dependencyPackages, ...vendoredPackages],
  };
}

function markdownRow(name, version, licenses, publisher) {
  return `| ${name} | ${version} | ${licenses} | ${publisher} |`;
}

function buildSbomMd(packages, vendored) {
  const lines = [
    '# Software Bill of Materials',
    '',
    'Generated by scripts/generate-sbom.mjs — do not edit manually. The dependency',
    'data below is reused from [THIRD-PARTY-NOTICES.md](THIRD-PARTY-NOTICES.md)',
    '(regenerated with `pnpm notices` and enforced by `pnpm check:licenses`), so this',
    'document is consistent with the license scan. Machine-readable form:',
    '[sbom.spdx.json](sbom.spdx.json) (SPDX 2.3).',
    '',
    markdownRow('Package', 'Version', 'License', 'Publisher'),
    '| --- | --- | --- | --- |',
    ...packages.map((p) => markdownRow(p.name, p.version, p.license, p.publisher)),
    '',
    '## Vendored artifacts (not npm dependencies)',
    '',
    'The table above covers the installed dependency tree. The following artifacts are physically vendored into this repository and loaded at runtime; they are **not** npm dependencies, do not appear in the dependency graph, and are therefore not part of the license scan above. They are documented here so the license obligations travel with the project.',
    '',
    '| Artifact | Source | License | Verified by |',
    '| --- | --- | --- | --- |',
    ...vendored.map((v) => `| ${v.artifact} | ${v.source} | ${v.license} | ${v.verifiedBy} |`),
    '',
  ];
  return lines.join('\n');
}

function main() {
  let notices;
  try {
    notices = readFileSync(NOTICES_FILE, 'utf8');
  } catch {
    console.error(
      `[sbom] ${NOTICES_FILE} not found — run \`pnpm notices\` first (the SBOM reuses the ` +
        `license-scan data; check:licenses fails without it too).`,
    );
    process.exit(1);
  }

  const { packages, vendored } = parseNotices(notices);
  if (packages.length === 0) {
    console.error(`[sbom] no dependency rows parsed from ${NOTICES_FILE} — is it generated?`);
    process.exit(1);
  }

  const created = new Date().toISOString();
  const doc = buildSpdxDoc(packages, vendored, created);

  writeFileSync(SBOM_MD_FILE, buildSbomMd(packages, vendored), 'utf8');
  writeFileSync(SBOM_SPDX_FILE, `${JSON.stringify(doc, null, 2)}\n`, 'utf8');

  console.log(`[sbom] wrote ${SBOM_MD_FILE} (${packages.length} dependencies + ${vendored.length} vendored artifacts)`);
  console.log(`[sbom] wrote ${SBOM_SPDX_FILE} (SPDX-2.3, ${doc.packages.length} packages)`);
}

main();
